# Generated by Django 5.1.5 on 2025-01-31 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calcul',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
