# Generated by Django 5.1.5 on 2025-01-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('age', models.CharField(max_length=250, verbose_name='Возраст')),
                ('text', models.IntegerField(verbose_name='Текст')),
            ],
        ),
    ]
