# Generated by Django 5.1.5 on 2025-01-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='text',
            field=models.CharField(max_length=250, verbose_name='Текст'),
        ),
    ]
