# Generated by Django 5.1.5 on 2025-01-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_alter_test_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calcul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.IntegerField(verbose_name='Первое значение')),
                ('number2', models.IntegerField(verbose_name='Второе значение')),
                ('number3', models.IntegerField(verbose_name='Третье значение')),
            ],
        ),
    ]
