# Generated by Django 5.1.5 on 2025-01-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_calcul'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcul',
            name='rezult',
            field=models.IntegerField(default=1, verbose_name='Результат'),
            preserve_default=False,
        ),
    ]
