# Generated by Django 5.1.5 on 2025-01-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_calcul_rezult'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcul',
            name='rezultUser',
            field=models.IntegerField(default=1, verbose_name='Результат пользователя'),
            preserve_default=False,
        ),
    ]
