# Generated by Django 5.1.5 on 2025-01-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_calcul_rezultuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcul',
            name='count_zvezd',
            field=models.IntegerField(default=1, verbose_name='Количество заработанных звезд'),
            preserve_default=False,
        ),
    ]
